# -*- coffee -*- -p # emacs mode binding

name: coffee-bean
author: YC <yinso.chen@gmail.com>
description: Writing JSON in coffee-script format
version: 0.4.0
perferGlobal: true
bin:
  bean: "./bin/bean" # interpolation works.
main: './lib/bean.js'
scripts:
  prepublish: 'make'
dependencies:
  optimist: '=0.3.1'
  coffee-script: '=1.9.2'
  chai: '=1.4.2'
  underscore: '=1.3.1'
  js-yaml: '=3.2.2'
devDependencies:
  mocha: '=1.7.3'
license: 'MIT'
keywords:
  - package.json
  - configuration
  - coffee
  - bean
  - script
  - yaml
